name: Sign Whitelist

on:
  push:
    paths:
      - 'whitelist/whitelist.json'

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create signer script
        run: |
          cat << 'EOF' > sign.js
          const fs = require('fs');
          const crypto = require('crypto');

          const privateKey = process.env.WHITELISTED_PRIVATE;
          const data = fs.readFileSync('whitelist/whitelist.json');

          const sign = crypto.createSign('RSA-SHA256');
          sign.update(data);
          sign.end();

          const signature = sign.sign(privateKey, 'base64');
          fs.writeFileSync('whitelist/whitelist.sig', signature);

          console.log('Signature written to whitelist/whitelist.sig');
          EOF

      - name: Sign whitelist.json
        run: node sign.js

      - name: Commit signature
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add whitelist/whitelist.sig
          git commit -m "Update whitelist signature"
          git push
        env:
          WHITELISTED_PRIVATE: ${{ secrets.WHITELISTED_PRIVATE }}
