name: Sign Whitelist

on:
  push:
    paths:
      - 'whitelist/whitelist.json'

jobs:
  sign:
    runs-on: ubuntu-latest
    env:
      WHITELISTED_PRIVATE: ${{ secrets.WHITELISTED_PRIVATE }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create signer script
        run: |
          cat << 'EOF' > sign.js
          const fs = require('fs');
          const crypto = require('crypto');

          const privateKey = process.env.WHITELISTED_PRIVATE;
          if (!privateKey) {
            console.error("❌ ERROR: WHITELISTED_PRIVATE is missing!");
            process.exit(1);
          }

          console.log("ℹ️ Private key length:", privateKey.length);

          const data = fs.readFileSync('whitelist/whitelist.json');
          const sign = crypto.createSign('RSA-SHA256');
          sign.update(data);
          sign.end();

          try {
            const signature = sign.sign(privateKey, 'base64');
            fs.writeFileSync('whitelist/whitelist.sig', signature);
            console.log("✅ Signature written to whitelist/whitelist.sig");
          } catch (err) {
            console.error("❌ Signing failed:", err.message);
            process.exit(1);
          }
          EOF

      - name: Run signer
        run: node sign.js

      - name: Commit signature
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add whitelist/whitelist.sig
          git commit -m "Update whitelist signature" || echo "No changes to commit"
          git push
